# Generated by Django 5.0.1 on 2025-11-22 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('items', models.JSONField(default=list)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount_in_words', models.TextField()),
                ('tax_breakdown', models.JSONField(blank=True, default=list)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_pending', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payments', models.JSONField(default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'date'], name='invoices_company_19f52b_idx'), models.Index(fields=['client'], name='invoices_client__a0059b_idx'), models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx')],
            },
        ),
    ]
