# Generated by Django 5.0.1 on 2025-11-22 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=10, null=True)),
                ('hsn', models.CharField(help_text='HSN for goods, SAC for services', max_length=8)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('type', models.CharField(choices=[('product', 'Product (Goods)'), ('service', 'Service')], default='product', max_length=20)),
                ('has_serial_number', models.BooleanField(default=False)),
                ('category_id', models.UUIDField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'product_name'], name='products_company_77ae6f_idx'), models.Index(fields=['hsn'], name='products_hsn_70b439_idx')],
            },
        ),
    ]
